# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class Backend:
        name: str
        type: str
        url: str
    class Bucket:
        name: str
        type: str
    class Database:
        token: str
        type: str
        url: str
    class Model:
        name: str
        type: str
        url: str
    class Site:
        type: str
        url: str

