/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Backend": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Database": {
      "token": string
      "type": "sst.sst.Linkable"
      "url": string
    }
    "ModelBackend": {
      "service": string
      "type": "sst.aws.Service"
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
    "Site": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
